# Generated by Django 5.2 on 2025-06-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth_marksheet', models.FileField(upload_to='documents/marksheets/')),
                ('leaving_certificate', models.FileField(upload_to='documents/leaving/')),
                ('adhar_card', models.FileField(upload_to='documents/adhar/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
