# Generated by Django 5.2 on 2025-06-06 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_studentdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdocument',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='admission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.admission'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='adhar_card',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='leaving_certificate',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='tenth_marksheet',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
